import type { Metadata } from "next";
import { Lora, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ScrollNavbar from "@/components/ScrollNavbar";
import localFont from 'next/font/local'


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

// const quadraat = localFont({
//   src: '../assets/fonts/FFQuadraatPro-Regular.ttf',
//   variable: "--font-quadraat",
// })

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// })

const orpheus = localFont({
  src: '../assets/fonts/OrpheusPro-Bold.ttf',
  variable: "--font-orpheus",
})

const orpheusNormal = localFont({
  src: '../assets/fonts/OrpheusW05-Regular.ttf',
  variable: "--font-orpheusNormal",
})

const proximaNova = localFont({
  src: '../assets/fonts/ProximaNovaA-Light.ttf',
  variable: "--font-proximaNova",
})

const le_beaune = localFont({
  src: '../assets/fonts/LeBeauneNew.otf',
  variable: "--font-le_beaune",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${orpheus.variable} ${proximaNova.variable} ${orpheusNormal.variable} ${poppins.variable} ${le_beaune.variable} antialiased h-screen`}
      >
        {/* <Navbar/> */}
        <ScrollNavbar />
        {children}
      </body>
    </html>
  );
}
